MAP_WIDTH = 12
MAP_HEIGHT = 12

DIRECTIONS = [(1, 0), (-1, 0), (0, 1), (0, -1)]

EMPTY_CELL_ICON = "▢"
TREE_ICON = "T"
ROCK_ICON = "R"
GRASS_ICON = "G"
HERBIVORE_ICON = "H"
PREDATOR_ICON = "P"

STATIC_OBJECT_PROBABILITY = 0.05
RESOURCE_PROBABILITY = 0.3
CREATURE_PROBABILITY = 0.65

TREE_PROBABILITY = 0.5
ROCK_PROBABILITY = 0.5
GRASS_PROBABILITY = 1.0
HERBIVORE_PROBABILITY = 0.5
PREDATOR_PROBABILITY = 0.5