MAP_HEIGHT = 3
MAP_WIDTH = 3

TREE_ICON = "🌳"
GRASS_ICON = "🌿"
ROCK_ICON = "⛰️"
FREE_CELL_ICON = "🟩"

HERBIVORE_ICON = "🐇"
HERBIVORE_SPEED = 3
HERBIVORE_HP = 10

PREDATOR_ICON = "🦊"
PREDATOR_SPEED = 4
PREDATOR_HP = 10
PREDATOR_DAMAGE = 5